In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('data.csv')
df

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [3]:
df.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [4]:
df.tail()

SAT   GPA
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

In [5]:
df.dropna(inplace= True)

In [6]:
df.drop_duplicates(inplace= True)

In [7]:
df.isnull().sum()

SAT    0
GPA    0
dtype: int64

In [8]:
X = df.drop(columns = 'GPA')
Y = df.GPA

In [9]:
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X, Y, test_size = 0.2, random_state= 2)

In [10]:
lr = linear_model.LinearRegression()

In [11]:
lr.fit(Xtrain, Ytrain)

LinearRegression()

In [12]:
Xtest

SAT
28  2020
0   1714
29  1794
12  1735
77  2020
60  1964
83  2050
49  1979
26  1787
15  1872
24  1974
57  1953
71  1778
14  1773
63  2041
51  1855
46  1824

In [13]:
Ytest

28    3.28
0     2.40
29    3.28
12    3.08
77    3.65
60    3.49
83    3.81
49    3.41
26    3.28
15    3.17
24    3.24
57    3.47
71    3.59
14    3.12
63    3.51
51    3.42
46    3.40
Name: GPA, dtype: float64

In [14]:
lr.predict(Xtest.iloc[5].values.reshape(1,1))

c:\Users\AL-HAMD\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3.55875682])

In [15]:
plt.scatter(df.SAT, df.GPA)
plt.plot(Xtest, lr.predict(Xtest), color= 'red')
plt.xlabel("SAT")
plt.ylabel("GPA")

Text(0, 0.5, 'GPA')

In [16]:
# slope m
m = lr.coef_
m

array([0.00173021])

In [17]:
# intercept b
b = lr.intercept_
b

0.16061943810844737

In [18]:
y = m*X +b
y = m*1891 +b
y

array([3.43245131])